Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 608, in async_setup_kernel
    yield
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# read data
# You will need to install pyreadstat
# pip install pyreadstat
enapres2020_1 = pd.read_spss( r"../_data\enapres_2020_ch_100\736-Modulo1618\CAP_100_URBANO_RURAL_3.sav" )

# Get labels from sav file
# pip install savReaderWriter
import savReaderWriter as sav
with sav.SavHeaderReader( r"../_data\enapres_2020_ch_100\736-Modulo1618\CAP_100_URBANO_RURAL_3.sav", ioUtf8=True) as header:
    metadata = header.all()
    labels_enapres2020_1 = metadata.valueLabels
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[63], line 8[0m
[0;32m      4[0m enapres2020_1 [38;5;241m=[39m pd[38;5;241m.[39mread_spss( [38;5;124mr[39m[38;5;124m"[39m[38;5;124m../_data[39m[38;5;124m\[39m[38;5;124menapres_2020_ch_100[39m[38;5;124m\[39m[38;5;124m736-Modulo1618[39m[38;5;124m\[39m[38;5;124mCAP_100_URBANO_RURAL_3.sav[39m[38;5;124m"[39m )
[0;32m      6[0m [38;5;66;03m# Get labels from sav file[39;00m
[0;32m      7[0m [38;5;66;03m# pip install savReaderWriter[39;00m
[1;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01msavReaderWriter[39;00m [38;5;28;01mas[39;00m [38;5;21;01msav[39;00m
[0;32m      9[0m [38;5;28;01mwith[39;00m sav[38;5;241m.[39mSavHeaderReader( [38;5;124mr[39m[38;5;124m"[39m[38;5;124m../_data[39m[38;5;124m\[39m[38;5;124menapres_2020_ch_100[39m[38;5;124m\[39m[38;5;124m736-Modulo1618[39m[38;5;124m\[39m[38;5;124mCAP_100_URBANO_RURAL_3.sav[39m[38;5;124m"[39m, ioUtf8[38;5;241m=[39m[38;5;28;01mTrue[39;00m) [38;5;28;01mas[39;00m header:
[0;32m     10[0m     metadata [38;5;241m=[39m header[38;5;241m.[39mall()

File [1;32mC:\Python\Python311\Lib\site-packages\savReaderWriter\__init__.py:138[0m
[0;32m    136[0m [38;5;28;01mfrom[39;00m [38;5;21;01mheader[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m    137[0m [38;5;28;01mfrom[39;00m [38;5;21;01msavReader[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m--> 138[0m [38;5;28;01mfrom[39;00m [38;5;21;01msavWriter[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m    139[0m [38;5;28;01mfrom[39;00m [38;5;21;01msavHeaderReader[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m    140[0m [38;5;28;01mfrom[39;00m [38;5;21;01msavReaderNp[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [1;32mC:\Python\Python311\Lib\site-packages\savReaderWriter\savWriter.py:8[0m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mtime[39;00m
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mlocale[39;00m
[1;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m [38;5;28;01mimport[39;00m Iterable
[0;32m     10[0m [38;5;28;01mtry[39;00m:
[0;32m     11[0m     pandasOK [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[1;31mImportError[0m: cannot import name 'Iterable' from 'collections' (C:\Python\Python311\Lib\collections\__init__.py)
ImportError: cannot import name 'Iterable' from 'collections' (C:\Python\Python311\Lib\collections\__init__.py)

